### ISSUE TITLE
아카라이브 2차 인증 추가됨

### ISSUE THREAD

**Issue by Wintiger0222** [aldlfkahs/DCinsideAlarm#9]
아카라이브에 2차 인증이 추가되어 정상적으로 로그인이 안됩니다.
이 때문에 다시 비로그인 제한 게시물 알림이 정상적으로 보이지 않습니다.

**Comment by Wintiger0222** [comment]
https://github.com/Wintiger0222/DCinsideAlarm/commit/7858b71049dd5cbb3f0fa9594a480a99300a6a45
해당 커밋에서 크로미움 사용하도록 해서 해결해놓았습니다. 
검토 부탁드립니다.

**Comment by aldlfkahs** [comment]
죄송합니다 알림이 오지 않아서 이제서야 확인했네요.
첨부해주신 링크로 제가 복붙해도 되겠지만, 혹시 PR 형태로 요청해주실 수 있을까요?

**Comment by Wintiger0222** [comment]
그사이에 아카라이브 측에서 또 UI를 변경하여서 조금 수정후 PR 보내드리겠습니다.

**Comment by aldlfkahs** [comment]
또 바뀌었군요 ㅠㅠ 넵 PR 주시면 확인하겠습니다. 감사합니다!

**Comment by aldlfkahs** [comment]
https://github.com/aldlfkahs/DCinsideAlarm/pull/10
위 PR에서 이어집니다. 제보 및 PR주셔서 감사드립니다.
